version: '3.7'
services:
  app:
    build: .
    restart: on-failure
    depends_on:
      - postgresdb
      - redisdb
    ports:
      - '5000:5000'
    environment:
      LOCAL_DATABASE_URL: 'postgresql://bot:bot@postgresdb:5432/bot'
      REDIS_HOST: 'redisdb'
    networks:
      - webnet
  postgresdb:
    image: 'postgres'
    environment:
      POSTGRES_USER: 'bot'
      POSTGRES_PASSWORD: 'bot'
      POSTGRES_DB: 'bot'
    volumes:
      - './pgdata:/var/lib/postgresql/data'
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:5431"]
        interval: 5s
        timeout: 10s
        retries: 5
    networks:
      - webnet
  redisdb:
    image: 'redis'
    networks:
      - webnet
networks:
  webnet: